# Generated by Django 5.2.7 on 2026-09-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("en-route", "En-route"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("driver", "Driver"),
                            ("rider", "Rider"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                ("id_ride_event", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_events",
                        to="core.ride",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="id_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="id_rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_rider",
                to="core.user",
            ),
        ),
    ]
