# Generated by Django 5.2.7 on 2026-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="pickup_time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
